export const typeLabelMap: Record<string, string> = {
  bug: '벌레',
  dark: '악',
  dragon: '드래곤',
  electric: '전기',
  fairy: '페어리',
  fighting: '격투',
  fire: '불꽃',
  flying: '비행',
  ghost: '고스트',
  grass: '풀',
  ground: '땅',
  ice: '얼음',
  normal: '노말',
  poison: '독',
  psychic: '에스퍼',
  rock: '바위',
  steel: '강철',
  water: '물',
};

export const typeColorMap: Record<string, string> = {
  bug: 'bg-type-bug',
  dark: 'bg-type-dark',
  dragon: 'bg-type-dragon',
  electric: 'bg-type-electric',
  fairy: 'bg-[#EE99AC]',
  fighting: 'bg-type-fight',
  fire: 'bg-type-fire',
  flying: 'bg-type-flying',
  ghost: 'bg-type-ghost',
  grass: 'bg-type-grass',
  ground: 'bg-type-ground',
  ice: 'bg-type-ice',
  normal: 'bg-type-normal',
  poison: 'bg-type-poison',
  psychic: 'bg-type-psychic',
  rock: 'bg-type-rock',
  steel: 'bg-type-steel',
  water: 'bg-type-water',
};

export const typeIconMap: Record<string, string> = {
  bug: '/images/pokemon-types/bug.svg',
  dark: '/images/pokemon-types/dark.svg',
  dragon: '/images/pokemon-types/dragon.svg',
  electric: '/images/pokemon-types/electric.svg',
  fairy: '/images/pokemon-types/fairy.svg',
  fighting: '/images/pokemon-types/fighting.svg',
  fire: '/images/pokemon-types/fire.svg',
  flying: '/images/pokemon-types/flying.svg',
  ghost: '/images/pokemon-types/ghost.svg',
  grass: '/images/pokemon-types/grass.svg',
  ground: '/images/pokemon-types/ground.svg',
  ice: '/images/pokemon-types/ice.svg',
  normal: '/images/pokemon-types/normal.svg',
  poison: '/images/pokemon-types/poison.svg',
  psychic: '/images/pokemon-types/psychic.svg',
  rock: '/images/pokemon-types/rock.svg',
  steel: '/images/pokemon-types/steel.svg',
  water: '/images/pokemon-types/water.svg',
};
