'use server';

import { RecommendRequestSchema } from '@/features/deck-recommendation/model/schemas';
import type { RecommendResponse, RosterPokemon } from '@/features/deck-recommendation/model/schemas';
import { filterOptimal, filterStatus, filterCounter } from '@/features/deck-recommendation/lib/rule-engine';
import { generateRecommendation, RECOMMENDATION_MODEL } from '@/features/deck-recommendation/lib/gemini';
import { fallbackRecommendation } from '@/features/deck-recommendation/lib/fallback';

const MOCK_ROSTER: RosterPokemon[] = [
  // ── grass/poison ─────────────────────────────────────────────────────────
  {
    dexId: 3,
    koName: '이상해꽃',
    artworkUrl: '',
    type1: 'grass',
    type2: 'poison',
    level: 45,
    baseAtk: 80,
    baseSpd: 80,
    baseStatTotal: 525,
    moves: [
      { id: 'solar-beam', koName: '솔라빔', type: 'grass', power: 120, statusEffect: null },
      { id: 'sludge-bomb', koName: '오물폭탄', type: 'poison', power: 90, statusEffect: null },
      { id: 'sleep-powder', koName: '수면가루', type: 'grass', power: null, statusEffect: 'status' },
      { id: 'synthesis', koName: '광합성', type: 'grass', power: null, statusEffect: null },
    ],
  },
  {
    dexId: 407,
    koName: '로즈레이드',
    artworkUrl: '',
    type1: 'grass',
    type2: 'poison',
    level: 40,
    baseAtk: 80,
    baseSpd: 80,
    baseStatTotal: 515,
    moves: [
      { id: 'petal-dance', koName: '꽃잎댄스', type: 'grass', power: 120, statusEffect: null },
      { id: 'sludge-bomb', koName: '오물폭탄', type: 'poison', power: 90, statusEffect: null },
      { id: 'sleep-powder', koName: '수면가루', type: 'grass', power: null, statusEffect: 'status' },
      { id: 'shadow-ball', koName: '섀도볼', type: 'ghost', power: 80, statusEffect: null },
    ],
  },
  // ── fire ─────────────────────────────────────────────────────────────────
  {
    dexId: 6,
    koName: '리자몽',
    artworkUrl: '',
    type1: 'fire',
    type2: 'flying',
    level: 50,
    baseAtk: 80,
    baseSpd: 80,
    baseStatTotal: 534,
    moves: [
      { id: 'flamethrower', koName: '화염방사', type: 'fire', power: 90, statusEffect: null },
      { id: 'air-slash', koName: '에어슬래시', type: 'flying', power: 75, statusEffect: null },
      { id: 'dragon-claw', koName: '드래곤크로', type: 'dragon', power: 80, statusEffect: null },
      { id: 'fire-blast', koName: '불대문자', type: 'fire', power: 110, statusEffect: null },
    ],
  },
  {
    dexId: 146,
    koName: '파이어',
    artworkUrl: '',
    type1: 'fire',
    type2: 'flying',
    level: 60,
    baseAtk: 80,
    baseSpd: 80,
    baseStatTotal: 580,
    moves: [
      { id: 'fire-blast', koName: '불대문자', type: 'fire', power: 110, statusEffect: null },
      { id: 'flamethrower', koName: '화염방사', type: 'fire', power: 90, statusEffect: null },
      { id: 'air-slash', koName: '에어슬래시', type: 'flying', power: 75, statusEffect: null },
      { id: 'ancient-power', koName: '원시의힘', type: 'rock', power: 60, statusEffect: null },
    ],
  },
  // ── water ─────────────────────────────────────────────────────────────────
  {
    dexId: 9,
    koName: '거북왕',
    artworkUrl: '',
    type1: 'water',
    type2: null,
    level: 50,
    baseAtk: 80,
    baseSpd: 80,
    baseStatTotal: 530,
    moves: [
      { id: 'surf', koName: '파도타기', type: 'water', power: 90, statusEffect: null },
      { id: 'hydro-pump', koName: '하이드로펌프', type: 'water', power: 110, statusEffect: null },
      { id: 'ice-beam', koName: '냉동빔', type: 'ice', power: 90, statusEffect: null },
      { id: 'flash-cannon', koName: '미러샷', type: 'steel', power: 80, statusEffect: null },
    ],
  },
  {
    dexId: 382,
    koName: '가이오가',
    artworkUrl: '',
    type1: 'water',
    type2: null,
    level: 70,
    baseAtk: 80,
    baseSpd: 80,
    baseStatTotal: 680,
    moves: [
      { id: 'hydro-pump', koName: '하이드로펌프', type: 'water', power: 110, statusEffect: null },
      { id: 'ice-beam', koName: '냉동빔', type: 'ice', power: 90, statusEffect: null },
      { id: 'thunder', koName: '천둥', type: 'electric', power: 110, statusEffect: null },
      { id: 'sheer-cold', koName: '절대영도', type: 'ice', power: null, statusEffect: 'status' },
    ],
  },
  {
    dexId: 260,
    koName: '대짱이',
    artworkUrl: '',
    type1: 'water',
    type2: 'ground',
    level: 45,
    baseAtk: 80,
    baseSpd: 80,
    baseStatTotal: 535,
    moves: [
      { id: 'earthquake', koName: '지진', type: 'ground', power: 100, statusEffect: null },
      { id: 'surf', koName: '파도타기', type: 'water', power: 90, statusEffect: null },
      { id: 'ice-beam', koName: '냉동빔', type: 'ice', power: 90, statusEffect: null },
      { id: 'yawn', koName: '하품', type: 'normal', power: null, statusEffect: 'status' },
    ],
  },
  // ── electric ──────────────────────────────────────────────────────────────
  {
    dexId: 25,
    koName: '피카츄',
    artworkUrl: '',
    type1: 'electric',
    type2: null,
    level: 30,
    baseAtk: 80,
    baseSpd: 80,
    baseStatTotal: 320,
    moves: [
      { id: 'thunderbolt', koName: '10만볼트', type: 'electric', power: 90, statusEffect: null },
      { id: 'thunder', koName: '천둥', type: 'electric', power: 110, statusEffect: null },
      { id: 'quick-attack', koName: '전광석화', type: 'normal', power: 40, statusEffect: null },
      { id: 'thunder-wave', koName: '전기자석파', type: 'electric', power: null, statusEffect: 'status' },
    ],
  },
  {
    dexId: 145,
    koName: '썬더',
    artworkUrl: '',
    type1: 'electric',
    type2: 'flying',
    level: 60,
    baseAtk: 80,
    baseSpd: 80,
    baseStatTotal: 580,
    moves: [
      { id: 'thunder', koName: '천둥', type: 'electric', power: 110, statusEffect: null },
      { id: 'thunderbolt', koName: '10만볼트', type: 'electric', power: 90, statusEffect: null },
      { id: 'air-slash', koName: '에어슬래시', type: 'flying', power: 75, statusEffect: null },
      { id: 'thunder-wave', koName: '전기자석파', type: 'electric', power: null, statusEffect: 'status' },
    ],
  },
  {
    dexId: 462,
    koName: '자포코일',
    artworkUrl: '',
    type1: 'electric',
    type2: 'steel',
    level: 45,
    baseAtk: 80,
    baseSpd: 80,
    baseStatTotal: 535,
    moves: [
      { id: 'thunderbolt', koName: '10만볼트', type: 'electric', power: 90, statusEffect: null },
      { id: 'flash-cannon', koName: '플래시캐논', type: 'steel', power: 80, statusEffect: null },
      { id: 'thunder-wave', koName: '전기자석파', type: 'electric', power: null, statusEffect: 'status' },
      { id: 'tri-attack', koName: '트라이어택', type: 'normal', power: 80, statusEffect: null },
    ],
  },
  // ── ice ───────────────────────────────────────────────────────────────────
  {
    dexId: 144,
    koName: '프리져',
    artworkUrl: '',
    type1: 'ice',
    type2: 'flying',
    level: 60,
    baseAtk: 80,
    baseSpd: 80,
    baseStatTotal: 580,
    moves: [
      { id: 'blizzard', koName: '눈보라', type: 'ice', power: 110, statusEffect: null },
      { id: 'ice-beam', koName: '냉동빔', type: 'ice', power: 90, statusEffect: null },
      { id: 'air-slash', koName: '에어슬래시', type: 'flying', power: 75, statusEffect: null },
      { id: 'powder-snow', koName: '가루눈', type: 'ice', power: null, statusEffect: 'status' },
    ],
  },
  {
    dexId: 478,
    koName: '포푸니라',
    artworkUrl: '',
    type1: 'ice',
    type2: 'ghost',
    level: 40,
    baseAtk: 80,
    baseSpd: 80,
    baseStatTotal: 480,
    moves: [
      { id: 'blizzard', koName: '눈보라', type: 'ice', power: 110, statusEffect: null },
      { id: 'shadow-ball', koName: '섀도볼', type: 'ghost', power: 80, statusEffect: null },
      { id: 'will-o-wisp', koName: '귀신불', type: 'fire', power: null, statusEffect: 'status' },
      { id: 'ice-shard', koName: '얼음뭉치', type: 'ice', power: 40, statusEffect: null },
    ],
  },
  // ── fighting ──────────────────────────────────────────────────────────────
  {
    dexId: 448,
    koName: '루카리오',
    artworkUrl: '',
    type1: 'fighting',
    type2: 'steel',
    level: 50,
    baseAtk: 80,
    baseSpd: 80,
    baseStatTotal: 535,
    moves: [
      { id: 'aura-sphere', koName: '파동탄', type: 'fighting', power: 80, statusEffect: null },
      { id: 'close-combat', koName: '인파이트', type: 'fighting', power: 120, statusEffect: null },
      { id: 'bullet-punch', koName: '머신펀치', type: 'steel', power: 40, statusEffect: null },
      { id: 'shadow-ball', koName: '섀도볼', type: 'ghost', power: 80, statusEffect: null },
    ],
  },
  {
    dexId: 214,
    koName: '헤라크로스',
    artworkUrl: '',
    type1: 'bug',
    type2: 'fighting',
    level: 40,
    baseAtk: 80,
    baseSpd: 80,
    baseStatTotal: 500,
    moves: [
      { id: 'close-combat', koName: '인파이트', type: 'fighting', power: 120, statusEffect: null },
      { id: 'x-scissor', koName: '크로스치기', type: 'bug', power: 80, statusEffect: null },
      { id: 'stone-edge', koName: '스톤에지', type: 'rock', power: 100, statusEffect: null },
      { id: 'night-slash', koName: '섀도크로', type: 'dark', power: 70, statusEffect: null },
    ],
  },
  // ── psychic ───────────────────────────────────────────────────────────────
  {
    dexId: 150,
    koName: '뮤츠',
    artworkUrl: '',
    type1: 'psychic',
    type2: null,
    level: 70,
    baseAtk: 80,
    baseSpd: 80,
    baseStatTotal: 680,
    moves: [
      { id: 'psychic', koName: '사이코키네시스', type: 'psychic', power: 90, statusEffect: null },
      { id: 'shadow-ball', koName: '섀도볼', type: 'ghost', power: 80, statusEffect: null },
      { id: 'ice-beam', koName: '냉동빔', type: 'ice', power: 90, statusEffect: null },
      { id: 'aura-sphere', koName: '파동탄', type: 'fighting', power: 80, statusEffect: null },
    ],
  },
  {
    dexId: 151,
    koName: '뮤',
    artworkUrl: '',
    type1: 'psychic',
    type2: null,
    level: 60,
    baseAtk: 80,
    baseSpd: 80,
    baseStatTotal: 600,
    moves: [
      { id: 'psychic', koName: '사이코키네시스', type: 'psychic', power: 90, statusEffect: null },
      { id: 'flamethrower', koName: '화염방사', type: 'fire', power: 90, statusEffect: null },
      { id: 'ice-beam', koName: '냉동빔', type: 'ice', power: 90, statusEffect: null },
      { id: 'earthquake', koName: '지진', type: 'ground', power: 100, statusEffect: null },
    ],
  },
  {
    dexId: 249,
    koName: '루기아',
    artworkUrl: '',
    type1: 'psychic',
    type2: 'flying',
    level: 70,
    baseAtk: 80,
    baseSpd: 80,
    baseStatTotal: 680,
    moves: [
      { id: 'aeroblast', koName: '에어로블라스트', type: 'flying', power: 100, statusEffect: null },
      { id: 'psychic', koName: '사이코키네시스', type: 'psychic', power: 90, statusEffect: null },
      { id: 'ice-beam', koName: '냉동빔', type: 'ice', power: 90, statusEffect: null },
      { id: 'recover', koName: '자기회복', type: 'normal', power: null, statusEffect: null },
    ],
  },
  // ── ghost ─────────────────────────────────────────────────────────────────
  {
    dexId: 94,
    koName: '팬텀',
    artworkUrl: '',
    type1: 'ghost',
    type2: 'poison',
    level: 45,
    baseAtk: 80,
    baseSpd: 80,
    baseStatTotal: 500,
    moves: [
      { id: 'shadow-ball', koName: '섀도볼', type: 'ghost', power: 80, statusEffect: null },
      { id: 'sludge-bomb', koName: '오물폭탄', type: 'poison', power: 90, statusEffect: null },
      { id: 'hypnosis', koName: '최면술', type: 'psychic', power: null, statusEffect: 'status' },
      { id: 'dark-pulse', koName: '암흑의파동', type: 'dark', power: 80, statusEffect: null },
    ],
  },
  // ── dragon ────────────────────────────────────────────────────────────────
  {
    dexId: 149,
    koName: '망나뇽',
    artworkUrl: '',
    type1: 'dragon',
    type2: 'flying',
    level: 55,
    baseAtk: 80,
    baseSpd: 80,
    baseStatTotal: 600,
    moves: [
      { id: 'dragon-rush', koName: '역린', type: 'dragon', power: 100, statusEffect: null },
      { id: 'ice-punch', koName: '아이스펀치', type: 'ice', power: 75, statusEffect: null },
      { id: 'thunder', koName: '천둥', type: 'electric', power: 110, statusEffect: null },
      { id: 'fire-punch', koName: '파이어펀치', type: 'fire', power: 75, statusEffect: null },
    ],
  },
  {
    dexId: 373,
    koName: '보만다',
    artworkUrl: '',
    type1: 'dragon',
    type2: 'flying',
    level: 55,
    baseAtk: 80,
    baseSpd: 80,
    baseStatTotal: 600,
    moves: [
      { id: 'dragon-rush', koName: '역린', type: 'dragon', power: 100, statusEffect: null },
      { id: 'flamethrower', koName: '화염방사', type: 'fire', power: 90, statusEffect: null },
      { id: 'fly', koName: '날기', type: 'flying', power: 90, statusEffect: null },
      { id: 'earthquake', koName: '지진', type: 'ground', power: 100, statusEffect: null },
    ],
  },
  {
    dexId: 384,
    koName: '레쿠쟈',
    artworkUrl: '',
    type1: 'dragon',
    type2: 'flying',
    level: 70,
    baseAtk: 80,
    baseSpd: 80,
    baseStatTotal: 680,
    moves: [
      { id: 'dragon-ascent', koName: '용승천', type: 'flying', power: 120, statusEffect: null },
      { id: 'dragon-claw', koName: '드래곤크로', type: 'dragon', power: 80, statusEffect: null },
      { id: 'extreme-speed', koName: '순간이동', type: 'normal', power: 80, statusEffect: null },
      { id: 'air-slash', koName: '에어슬래시', type: 'flying', power: 75, statusEffect: null },
    ],
  },
  {
    dexId: 445,
    koName: '한카리아스',
    artworkUrl: '',
    type1: 'dragon',
    type2: 'ground',
    level: 55,
    baseAtk: 80,
    baseSpd: 80,
    baseStatTotal: 600,
    moves: [
      { id: 'earthquake', koName: '지진', type: 'ground', power: 100, statusEffect: null },
      { id: 'dragon-claw', koName: '드래곤크로', type: 'dragon', power: 80, statusEffect: null },
      { id: 'stone-edge', koName: '스톤에지', type: 'rock', power: 100, statusEffect: null },
      { id: 'fire-fang', koName: '화염니', type: 'fire', power: 65, statusEffect: null },
    ],
  },
  // ── rock/dark ─────────────────────────────────────────────────────────────
  {
    dexId: 248,
    koName: '마기라스',
    artworkUrl: '',
    type1: 'rock',
    type2: 'dark',
    level: 60,
    baseAtk: 80,
    baseSpd: 80,
    baseStatTotal: 700,
    moves: [
      { id: 'stone-edge', koName: '스톤에지', type: 'rock', power: 100, statusEffect: null },
      { id: 'crunch', koName: '깨물어부수기', type: 'dark', power: 80, statusEffect: null },
      { id: 'earthquake', koName: '지진', type: 'ground', power: 100, statusEffect: null },
      { id: 'fire-blast', koName: '불대문자', type: 'fire', power: 110, statusEffect: null },
    ],
  },
  // ── ground ────────────────────────────────────────────────────────────────
  {
    dexId: 383,
    koName: '그란돈',
    artworkUrl: '',
    type1: 'ground',
    type2: null,
    level: 70,
    baseAtk: 80,
    baseSpd: 80,
    baseStatTotal: 670,
    moves: [
      { id: 'earthquake', koName: '지진', type: 'ground', power: 100, statusEffect: null },
      { id: 'fire-blast', koName: '불대문자', type: 'fire', power: 110, statusEffect: null },
      { id: 'solar-beam', koName: '솔라빔', type: 'grass', power: 120, statusEffect: null },
      { id: 'ancient-power', koName: '원시의힘', type: 'rock', power: 60, statusEffect: null },
    ],
  },
  {
    dexId: 330,
    koName: '플라이곤',
    artworkUrl: '',
    type1: 'dragon',
    type2: 'ground',
    level: 40,
    baseAtk: 80,
    baseSpd: 80,
    baseStatTotal: 515,
    moves: [
      { id: 'earthquake', koName: '지진', type: 'ground', power: 100, statusEffect: null },
      { id: 'dragon-claw', koName: '드래곤크로', type: 'dragon', power: 80, statusEffect: null },
      { id: 'flamethrower', koName: '화염방사', type: 'fire', power: 90, statusEffect: null },
      { id: 'fly', koName: '날기', type: 'flying', power: 90, statusEffect: null },
    ],
  },
  // ── steel ─────────────────────────────────────────────────────────────────
  {
    dexId: 212,
    koName: '시저리아',
    artworkUrl: '',
    type1: 'bug',
    type2: 'steel',
    level: 40,
    baseAtk: 80,
    baseSpd: 80,
    baseStatTotal: 500,
    moves: [
      { id: 'x-scissor', koName: '크로스치기', type: 'bug', power: 80, statusEffect: null },
      { id: 'iron-head', koName: '아이언헤드', type: 'steel', power: 80, statusEffect: null },
      { id: 'bullet-punch', koName: '머신펀치', type: 'steel', power: 40, statusEffect: null },
      { id: 'night-slash', koName: '섀도크로', type: 'dark', power: 70, statusEffect: null },
    ],
  },
  {
    dexId: 395,
    koName: '엠페르트',
    artworkUrl: '',
    type1: 'water',
    type2: 'steel',
    level: 45,
    baseAtk: 80,
    baseSpd: 80,
    baseStatTotal: 530,
    moves: [
      { id: 'surf', koName: '파도타기', type: 'water', power: 90, statusEffect: null },
      { id: 'flash-cannon', koName: '플래시캐논', type: 'steel', power: 80, statusEffect: null },
      { id: 'earthquake', koName: '지진', type: 'ground', power: 100, statusEffect: null },
      { id: 'ice-beam', koName: '냉동빔', type: 'ice', power: 90, statusEffect: null },
    ],
  },
  // ── normal ────────────────────────────────────────────────────────────────
  {
    dexId: 143,
    koName: '잠만보',
    artworkUrl: '',
    type1: 'normal',
    type2: null,
    level: 40,
    baseAtk: 80,
    baseSpd: 80,
    baseStatTotal: 540,
    moves: [
      { id: 'body-slam', koName: '몸통박치기', type: 'normal', power: 85, statusEffect: null },
      { id: 'yawn', koName: '하품', type: 'normal', power: null, statusEffect: 'status' },
      { id: 'earthquake', koName: '지진', type: 'ground', power: 100, statusEffect: null },
      { id: 'ice-beam', koName: '냉동빔', type: 'ice', power: 90, statusEffect: null },
    ],
  },
];

export async function testRecommendDeck(rawInput: unknown): Promise<RecommendResponse> {
  const parsed = RecommendRequestSchema.safeParse(rawInput);
  if (!parsed.success) {
    return { ok: false, message: parsed.error.issues[0]?.message ?? '입력값을 확인해주세요' };
  }
  const req = parsed.data;

  let candidates: RosterPokemon[];
  if (req.theme === 'status') {
    candidates = filterStatus(MOCK_ROSTER);
  } else if (req.theme === 'counter') {
    candidates = filterCounter(MOCK_ROSTER, req.counterTarget!);
  } else {
    candidates = filterOptimal(MOCK_ROSTER);
  }

  const aiResult = await generateRecommendation(req, candidates);
  const result = aiResult ?? fallbackRecommendation(req, candidates);

  return {
    ok: true,
    data: result,
    cached: false,
    model: aiResult ? RECOMMENDATION_MODEL : 'fallback',
  };
}
